### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#190]

**Comment by philschanely** [comment]
- [ ] Investigate focus state revision to differentiate between keyboard focus and mouse focus.

**Comment by philschanely** [comment]
Revising button interactions

- [ ] Focus state
- [ ] Active state
- [ ] Save state / loader

**Comment by samcroswell** [comment]
<img width="1054" alt="Screen Shot 2021-01-21 at 4 35 29 PM" src="https://user-images.githubusercontent.com/74267385/105429701-ca635a00-5c06-11eb-84e8-7f4a0fdb6cab.png">

### Proposed Button Updates

Below is a screen recording of Stripe's admin in Safari and is the ideal way I'd like us to handle our button interactions. It looks like the focus rings only show when tabbing through the UI or on certain elements like input fields, instead of every time you click on something. However, when viewing the Stripe admin in Chrome, these focus rings show on click for every element. If this is a technical or browser limitation that is fine, but I think I'd prefer whatever we implement to be the same experience across all browsers.
- Screen recording here: https://www.dropbox.com/s/fnpealli1au9jme/Stripe-interactions.mov?dl=0

With that being said I also like the focus styling they use. Our current implementation feels too heavy-handed and could be more subtle. I took a stab at redefining these states in Figma.

- Figma file here: https://www.figma.com/file/SCZt9jMd7OcTMrNsOFifDp/Sage-Components-WIP?node-id=2828%3A0
