### ISSUE TITLE
[Improvement] DISCOVERY: Implement TypeScript

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#740]
## Description

To improve the developer experience on the front-end and to fulfill the request from developers, this issue is to run discovery and a proof of concept around implementing TypeScript. 

_Note: converting to TypeScript can be incremental, so that existing JavaScript can be in place and not break._

## Objectives  

- [ ] What is important in our config file for TypeScript?
- [ ] How does TypeScript work with our build tools?
- [ ] Convert a component to TypeScript and verify it's working properly
- [ ] Note any potential issues
- [ ] Documentation

## Additional Information

* [TypeScript migration](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html)
* [TypeScript & React](https://www.typescriptlang.org/docs/handbook/react.html)

**Reach out to Developer Experience (@voodooGQ) for help here and verify setup**

**Comment by philschanely** [comment]
I will say I have worked extensively with Typescript in other projects and would caution against this much to @voodooGQ 's chagrin. The only immediate benefit I see is the possible type hinting that is built into VSCode.

Hangups include:

1. It adds a significant overhead to writing components that involve a learning curve for anyone writing the component. IMO this is not necessary for enforcing quality in the components and leads to mostly extra time spit-shining the typings. PropTypes do the trick for now.
2. It involves some additional work to create the tokens system that we have in place now. This effort would either mean moving away from and refactoring a lot of how we're doing things now with react tokens (such as Button.COLORS...), or rearchitecturing the system in its place. The benefit does not outweigh the work here IMO.
3. As of yet, I've heard no word of going to typescript in `kp` which also means an extra barrier for any such devs to write for our system. On the plus side, most likely any of our JS devs have also worked with Typescript in other jobs. Bottom line here is I'd like to know much more about Kajabi's interest in using Typescript at-large before I'd feel good about this aspect.

All this said I'm happy to be involved and greatly value the discussion of pros and cons with a sight to the end goal of a) `kp` devs finding our components easy to use and understand and b) the components themselves being easy for UXD, etc. to maintain.

**Comment by voodooGQ** [comment]
@philschanely Here's a fairly good article that goes over the pros/cons of Typescript: https://www.altexsoft.com/blog/typescript-pros-and-cons/. I think there's plenty of other benefits that go beyond basic type hinting, and I think it's ideally something we should move to as a company because it's primary benefit is catching bugs early/often in a compiled typesetting.

To address the hangups specifically:
1. Proptypes are a rudimentary version of what Typescript is ultimately trying to do. Does it do the trick? Yes, I'd say it does, but it probably should be improved upon if it can be. I would disagree about the "enforcing quality" statement, Typescript is very much about enforcing quality just at its roots.
2. Disagree here. Typescript can be added incrementally. You never have to change the way your token system works. You can if you want to, and there probably will be benefits for doing so, but it's not required.
3. Yeah this is a valid point, we have no plans to move to TS in `kp` though I think it's something we should consider. That being said there's a lot of things we're doing over on the Sage side of things that we're not doing on `kp` and honestly I don't see any real problem with that as long as we clearly document the expectations.

No matter what kind of new thing we throw at Sage there's gonna be a learning curve. With all the benefits Typescript provides I think it's wise for us to explore the possibility of integrating it and utilizing those benefits.

**Comment by kajabimark** [comment]
I haven't worked on `sage-lib`, but the Commerce team is interested in adding TypeScript support to `kp`. I even started doing a little research to see what is involved in adding that support.

**Comment by voodooGQ** [comment]
We're actively using it for the Production Engineering Bot currently as well if you'd like to look over an example: https://github.com/Kajabi/kajabi-serverless/tree/main/devops.sls

**Comment by philschanely** [comment]
This is helpful answering the Kajabi perspective. Thanks gents.

**Comment by philschanely** [comment]
Planning to look into this next week. I believe that also working in [Style Dictionary](https://amzn.github.io/style-dictionary/#/) will be beneficial here in generating shared tokens from a single source so I will try to get a POC for that going first.

**Comment by voodooGQ** [comment]
Initial draft pass at a Typescript POC: https://github.com/Kajabi/sage-lib/pull/841

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-61
