### ISSUE TITLE
[Improvement] Include a Figma reference on all components pages

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#755]
## Description

To create parity with Figma and the Design System, all components need Figma links or embedded design files.

### Figma Embed in a tab

![tab-right](https://user-images.githubusercontent.com/24237393/131724335-bb312d65-2917-437b-9d06-69d21522907b.png)

![tab-open](https://user-images.githubusercontent.com/24237393/131724378-4ccfb88a-fc4b-4a97-8313-192fc51403c4.png)

--- 

### Scroll-to Embed 

![Screen Shot 2021-08-30 at 4 15 28 PM](https://user-images.githubusercontent.com/24237393/131406817-a158a74e-6b23-4bd3-bdfb-dd02b1048756.png)

https://user-images.githubusercontent.com/24237393/131533817-e6638494-c022-44ab-a111-b19d71c35219.mp4

**Comment by FuturaExtraBold** [comment]
I like it, though I'd go with "Figma Designs".

**Comment by monicawheeler** [comment]
@FuturaExtraBold - agreed!

**Comment by anechol** [comment]
I really love this implementation. How would you feel about this tab being the last one in the list? I think the icon is throwing me off a bit being in the middle of the list but I don't know where else this tab can go because where it is now makes the most logical sense. But I love the icon :\

<img width="737" alt="Screen Shot 2021-08-31 at 4 20 48 PM" src="https://user-images.githubusercontent.com/14791307/131577643-e42c337d-ae36-44ab-bb81-5df14aa2c017.png">

**Comment by FuturaExtraBold** [comment]
The icon is throwing me off a tad. Maybe it could be smaller? Then you'd have to shrink the React icon, too. Hmmm...

**Comment by monicawheeler** [comment]
@anechol and @FuturaExtraBold - Totally agree. The icon does feel a bit out of place. Let me try your suggestions and post back here!
